[project]
name = "yen-flow-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cot-reports>=0.1.3",
    "jupyterlab>=4.3.6",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
]
