name: weekly update

on:
  workflow_dispatch: # 手動で実行するためのトリガー

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Create .venv
        run: uv sync

      - name: Run Python
        run: uv run main.py