name: weekly update

on:
  schedule:
    - cron: '0 0 * * 0' # 毎週日曜日の0時0分に実行
  workflow_dispatch: # 手動で実行するためのトリガー

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Create .venv
        run: uv sync

      - name: Run Python
        run: uv run main.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update HTML files" || echo "No changes to commit"
          git push